### ISSUE TITLE
Criar models das lotações 

### ISSUE THREAD

**Issue by arthurarp** [DITGO/2020-2-SiGeD#10]
ÉPICO: Lotações

Atividades:
- Criar arquivo das models para as lotações.

- Deve conter os atributos: id nome e descrição. (Os campos devem ser obrigatórios)
- Atualizar model do cliente

Critérios de aceitação:

- Relacionar com o cliente.

**Comment by lucaslop** [comment]
Foi criado a model de lotação [Commit - ](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/commit/1ede3c8f036851be2846520edecf2eada19a31a2). No arquivo [Arquivo](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/blob/1ede3c8f036851be2846520edecf2eada19a31a2/src/Models/LotacaoSchema.js)

Foi relacionado as models no [Commit](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/commit/1ede3c8f036851be2846520edecf2eada19a31a2). No [Arquivo](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/blob/1ede3c8f036851be2846520edecf2eada19a31a2/src/Models/ClientSchema.js)
