### ISSUE TITLE
Criar controllers para as lotações

### ISSUE THREAD

**Issue by arthurarp** [DITGO/2020-2-SiGeD#11]
ÉPICO: Lotações

Atividades:
- Criar arquivo das controllers para as lotações.

- Create
- Delete
- Update
- Read

Critérios de aceitação:

- Endpoints funcionando
- Atualizar documentação

**Comment by lucaslop** [comment]
Foi criado os controllers no [Commit](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/commit/77c227cb530a3d071e56be362d91023482391eb3). No [Arquivo](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/blob/11-controllers-lotacao/src/Controllers/LotacaoController.js) e atualizado o [controller](https://github.com/FGA-GCES/2020-2-SiGeD-Clients/blob/11-controllers-lotacao/src/Controllers/ClientController.js) de clientes.

As rotas criadas foram:

**POST:  `/lotacao/create`**
para criar uma nova lotação

```json
{
    "name": "Nome da lotação",
    "description": "Descrição da lotação",
}
```

**GET: `/lotacao`**

Para listar todas as lotações

**PUT: `/lotacao/update/:id`**

Para atualizar uma lotação passando o id como parâmetro 
```json
{
    "name": "Nome da lotação",
    "description": "Descrição da lotação"
}
```

**DELETE: `/lotacao/delete/:id`**
Para deletar uma lotação passando o id como parâmetro


Além disso, foi atualizado as rotas de clients. Agora, para cadastrar  um novo cliente, é necessário passar o id da lotação.

Exemplo:


```json
{
    "name": "Nome do Cliente",
    "cpf": "00000000000",
    "email": "cliente@email.com",
    "phone": "999999999",
    "office": "Cargo",
    "policeStation": "Locação",
    "city": "Cidade"
    "lotacao": "6d4e8ded5e8de8d55de"
}
```
