### ISSUE TITLE
Criar protótipos (Home, Lotações e Cargos)

### ISSUE THREAD

**Issue by arthurarp** [DITGO/2020-2-SiGeD#15]
Criar protótipo da página home, lotações e cargos.

Atividades:
Página home deve conter um menu (Tabelas) com um drop down com os seguintes itens(lotações e cargos)

Critérios:
- Seguir o padrão do site
- Utilizar a paleta de cores do projeto

**Comment by Wictorgirardi** [comment]
Tarefa concluida em https://www.figma.com/file/BEQP3AOu73t05muuaq63QS/Untitled?node-id=0%3A1
