### ISSUE TITLE
Lotação

### ISSUE THREAD

**Issue by DITGO** [DITGO/2020-2-SiGeD#7]
## Épico: Lotação

Registro de lotações (atualmente foram incluídos no código do sistema).

## História de usuário:

Eu, como usuário, desejo cadastrar lotação (departamentos onde o cliente trabalha)
Eu, como usuário, desejo visualizar lotação
Eu, como usuário, desejo editar lotação
Eu, como usuário, desejo deletar lotação
Eu, como usuário, desejo adicionar lotação ao cliente

**Comment by arthurarp** [comment]
Lotação

**Comment by arthurarp** [comment]
criar as models e o crud
